paragraphs_content = [
    ("text", "Ultratovush to'lqinlari — bu inson qulog'i eshita olmaydigan, chastotasi 20 kHz dan yuqori bo'lgan mexanik to'lqinlardir. Inson eshitish diapazoni 20 Hz dan 20 kHz gacha bo'lib, undan yuqori chastotadagi tovush to'lqinlari ultratovush deb ataladi. Sanoatda va IoT tizimlarida eng ko'p qo'llaniladigan chastota 40 kHz hisoblanadi, chunki bu chastotada to'lqin havoda yaxshi tarqaladi, qattiq jismlardan samarali aks etadi va atrof-muhitdagi shovqinlardan kam ta'sirlanadi. Ultratovush to'lqinlarining havoda tarqalish tezligi haroratga bevosita bog'liq bo'lib, v = 331.3 + 0.606 × T formulasi bilan aniq hisoblanadi, bu yerda T — Selsiy bo'yicha harorat darajasi. Masalan, 20°C haroratda tovush tezligi 343.5 m/s ga, 0°C da 331.3 m/s ga, 40°C da 355.5 m/s ga teng bo'ladi. Ultratovush sensorlari infraqizil (PIR) sensorlardan tubdan farq qiladi: infraqizil sensorlar issiqlik nurlanishini aniqlaydi va shisha orqali ishlamaydi, ob-havo sharoitlariga (yomg'ir, tuman, chang, qor) juda sezgir bo'ladi. Ultratovush sensorlari esa mexanik to'lqinlar bilan ishlaydi, shuning uchun optik to'siqlardan mustaqil ravishda ishlaydi. Bundan tashqari, ultratovush sensorlari ob'ektning rangi, materiali yoki sirt xususiyatlariga bog'liq emas — qora, oq, shaffof yoki yaltiroq jismlarni bir xil aniqlikda aniqlaydi, bu esa ko'cha yoritish tizimlarida muhim afzallik hisoblanadi."),

    ("text", "Ultratovush sensorlarining amaliy qo'llanilish sohalari juda keng: avtomobil sanoatida to'xtash sensori (parking sensor) sifatida, robototexnikada to'siqlarni aniqlash uchun, sanoat avtomatikasida suyuqlik sathini o'lchash uchun, tibbiyotda UZI (ultrasonografiya) diagnostikasi uchun va aqlli uy tizimlarida harakat aniqlash uchun ishlatiladi. Ko'cha yoritish tizimlarida ultratovush sensorlari PIR sensorlarga nisbatan bir qancha afzalliklarga ega: birinchidan, ular aniq masofani o'lchaydi (PIR faqat harakat bor/yo'q deydi), ikkinchidan, harorat o'zgarishlariga sezgir emas (PIR yozda issiq ob-havoda noto'g'ri ishlaydi), uchinchidan, ko'rish burchagi sozlanishi mumkin. Biroq, ultratovush sensorlarining ham kamchiliklari bor: juda yumshoq materiallar (mato, jun) tovushni yutadi va aks ettirmaydi, juda kichik ob'ektlar (hasharotlar, barglar) shovqin hosil qilishi mumkin, va bir nechta sensor yonma-yon o'rnatilganda o'zaro interferensiya yuzaga kelishi mumkin. Bu kamchiliklarni dasturiy filtrlash (debounce) mexanizmi orqali bartaraf etish mumkin."),

    ("text", "Masofa o'lchashning Time of Flight (ToF — parvoz vaqti) prinsipi ultratovush sensorlarining asosiy ishlash mexanizmi hisoblanadi. Bu jarayon quyidagi bosqichlardan iborat: birinchidan, mikrokontroller TRIG (trigger) pinga kamida 10 mikrosekundlik (μs) HIGH darajali signal yuboradi — bu sensor uchun ishga tushirish buyrug'i vazifasini bajaradi. Ikkinchidan, sensor ichidagi piezoelektrik generator bu signalni qabul qilib, ketma-ket 8 ta 40 kHz chastotali ultratovush impulsi chiqaradi — bu impulslar paket shaklida havoga tarqaladi. Uchinchidan, impulslar chiqishi bilan bir vaqtda ECHO pin HIGH holatiga o'tadi va vaqt hisobi boshlanadi. To'rtinchidan, impulslar havoda tarqalib, yo'lida uchraydigan birinchi qattiq jismga (odam, mashina, hayvon) urilib qaytadi. Beshinchidan, qaytgan signal sensorning qabul qiluvchi piezoelektrik elementi tomonidan aniqlanishi bilan ECHO pin LOW holatiga tushadi. Arduino muhitida pulseIn(ECHO, HIGH) funksiyasi orqali ECHO pinning HIGH holatida turgan vaqti mikrosekundlarda aniq o'lchanadi. Masofa hisoblash formulasi: d = t × 0.034 / 2, bu yerda t — mikrosekundlardagi vaqt, 0.034 — tovush tezligining sm/μs dagi qiymati (343 m/s = 0.0343 sm/μs), 2 ga bo'lish — signal ikki marta yo'l bosishi (borib-qaytish) uchun. Timeout qiymati odatda 30 ms (30000 μs) qilib belgilanadi, bu maksimal 510 sm masofaga mos keladi. Amaliy misollar: agar ECHO pin 580 μs davomida HIGH bo'lsa, masofa = 580 × 0.034 / 2 = 9.86 ≈ 10 sm; agar 11600 μs bo'lsa, masofa = 11600 × 0.034 / 2 = 197.2 ≈ 200 sm."),

    ("image", "ultrasonic_principle.png", "1.2-rasm. Ultratovush sensori ishlash prinsipi"),

    ("text", "RCWL-9610A ultratovush sensori Xitoyning Shenzhen shahrida joylashgan RCWL Electronics kompaniyasi tomonidan ishlab chiqarilgan bo'lib, IoT, robototexnika va embedded tizimlar uchun maxsus optimallashtirilgan zamonaviy sensordir. Sensorning ishlash kuchlanishi 3.0 V dan 5.5 V gacha keng oralig'ida bo'lib, bu ESP32 mikrokontrollerining 3.3V chiqishi bilan to'g'ridan-to'g'ri, hech qanday qo'shimcha kuchlanish o'zgartiruvchisiz ishlash imkonini beradi. Iste'mol toki 2 mA dan kam bo'lib, bu batareya yoki quyosh paneli bilan ishlaydigan avtonom tizimlar uchun juda muhim parametr hisoblanadi. O'lchash diapazoni 2 sm dan 450 sm gacha bo'lib, aniqlik ±1 sm darajasida — bu ko'cha yoritish tizimi uchun ortiqcha darajada yetarli. Ishlash chastotasi standart 40 kHz, trigger signal davomiyligi minimal 10 μs talab etiladi. Sensorning ko'rish burchagi 30° konus shaklida bo'lib, bu ko'cha sharoitida 3 metr balandlikda o'rnatilganda yerda taxminan 1.6 metr diametrli doirani qamraydi. Fizik o'lchamlari atigi 21×15 mm — bu HC-SR04 sensoridan 4 baravar kichik bo'lib, kompakt qurilmalarga osongina joylashadi. Ishlash harorati diapazoni -20°C dan +70°C gacha bo'lib, O'zbekistonning issiq yozlari va sovuq qishlarida ochiq havoda muammosiz ishlaydi. Ichki tuzilishida piezoelektrik element va keramik rezonator mavjud bo'lib, ular yuqori chastotali mexanik tebranishlarni hosil qiladi va qabul qiladi."),

    ("image", "rcwl9610a.png", "1.3-rasm. RCWL-9610A ultratovush sensori"),

    ("text", "RCWL-9610A sensorini tanlashda HC-SR04 bilan batafsil qiyoslash o'tkazildi, chunki HC-SR04 bozorda eng ko'p tarqalgan va arzon ultratovush sensori hisoblanadi. Biroq, HC-SR04 faqat 5V kuchlanishda ishlaydi va 15 mA tok iste'mol qiladi — bu RCWL-9610A ning 2 mA iste'moliga nisbatan 7.5 baravar ko'p. ESP32 mikrokontrolleri 3.3V mantiqiy darajada ishlagani uchun, HC-SR04 ni ulash uchun qo'shimcha level shifter (kuchlanish darajasini o'zgartiruvchi modul) kerak bo'ladi, bu esa sxemani murakkablashtiradi va ishonchlilikni kamaytiradi. HC-SR04 ning ko'rish burchagi atigi 15° bo'lib, juda tor maydonni qamraydi — 3 metr balandlikda faqat 80 sm diametrli doira. Fizik o'lchamlari 45×20 mm — bu kichik qurilmalarga o'rnatishni qiyinlashtiradi va estetik jihatdan ko'cha ustuniga mos kelmaydi. RCWL-9610A esa 3.0-5.5V oralig'ida ishlaydi, atigi 2 mA tok sarflaydi, 30° keng burchakka ega (3 metrda 1.6 m diametr) va 21×15 mm kompakt o'lchamda. Eng muhimi — uni ESP32 ga hech qanday qo'shimcha komponentlarsiz, to'g'ridan-to'g'ri ulash mumkin, bu esa ishlab chiqarish tannarxini kamaytiradi va tizim ishonchliligini oshiradi. Shuning uchun bu loyiha uchun RCWL-9610A tanlangan — u kam energiya sarflaydi, kichik o'lchamli, keng ko'rish burchagiga ega va ESP32 bilan to'liq elektrik mos keladi."),

    ("text", "TEMT6000 yorug'lik sensori Vishay Semiconductors kompaniyasi tomonidan ishlab chiqarilgan yuqori sifatli ambient light (atrof yorug'lik) fototransistori hisoblanadi. Sensor 360 nm (ultrabinafsha chegarasi) dan 970 nm (yaqin infraqizil) gacha bo'lgan to'lqin uzunliklarini qabul qiladi, maksimal sezuvchanlik 570 nm (yashil yorug'lik) da kuzatiladi — bu inson ko'zining spektral sezuvchanligiga juda yaqin bo'lib, sensorni kunduz/tun aniqlash uchun ideal qiladi. Ko'rish burchagi ±60° bo'lib, keng maydondan yorug'likni qabul qilish imkonini beradi — bu ko'cha yoritish tizimida muhim, chunki yorug'lik turli burchaklardan tushishi mumkin. Javob vaqti 1 ms dan kam — bu bulutlarning tez harakatlanishi yoki mashinalar faralarining o'tishi kabi tez o'zgarishlarni aniqlash uchun yetarli. Sensor analog chiqish beradi: 0V dan VCC gacha, yorug'lik intensivligiga to'g'ri proporsional. ESP32 ning ADC1_CH6 (GPIO34) kanaliga ulanganda, 12-bitli analog-raqamli konvertor (ADC) 0 dan 4095 gacha raqamli qiymat beradi. Tajribada aniqlangan chegaralar: 0-250 qiymati — qorong'u (tun vaqti), 350 dan yuqori — yorug' (kunduz vaqti), 250-350 orasida — alacalanish zonasi. Sensor photoelectric effect (fotoelektrik hodisa) prinsipi asosida ishlaydi: fotonlar yarimo'tkazgich materialga tushganda elektron-kovak juftliklari hosil bo'ladi, natijada kollektor-emitter orasidagi tok oqimi yorug'lik intensivligiga proporsional ravishda kuchayadi."),

    ("image", "temt6000.png", "1.4-rasm. TEMT6000 yorug'lik sensori"),

    ("text", "TEMT6000 sensorini loyihaga integratsiya qilishda uning ESP32 bilan ulanish sxemasi juda sodda: sensorning VCC pini ESP32 ning 3.3V chiqishiga, GND pini umumiy yerga, OUT (signal) pini esa GPIO34 (ADC1_CH6) ga ulanadi. GPIO34 faqat kirish (input-only) rejimida ishlaydigan pin bo'lib, ichki pull-up yoki pull-down rezistorlari yo'q — bu analog o'lchov uchun ideal, chunki hech qanday ichki qarshilik signal aniqligiga ta'sir qilmaydi. ADC konfiguratsiyasida 12-bit resolution (0-4095), 11dB attenuation (0-3.6V o'lchash diapazoni) sozlanadi. Amaliy kalibrlash jarayonida quyidagi natijalar olindi: to'liq qorong'ulikda (tun, yulduzli osmon) sensor 50-120 qiymat beradi, ko'cha chiroqlari yoniq bo'lganda 200-300, bulutli kunduz 400-600, ochiq kunduz 800-1500, to'g'ridan-to'g'ri quyosh nuri 3000-4095. Tizimda ikkita chegara belgilangan: 250 dan past — aniq tun (yoritgich ishlashi kerak), 350 dan yuqori — aniq kunduz (yoritgich kerak emas). Bu chegaralar Firebase orqali masofadan o'zgartirilishi mumkin, chunki turli geografik joylashuvlarda optimal qiymatlar farq qilishi mumkin."),

    ("text", "Sensorlarni tanlashda energiya samaradorligi asosiy mezon sifatida qo'yildi. Butun sensor tizimining umumiy tok iste'moli: RCWL-9610A — 2 mA (faqat o'lchov paytida, 150 ms har 500 ms da), TEMT6000 — 0.1 mA (doimiy), ESP32 deep sleep — 0.01 mA, ESP32 aktiv WiFi — 160 mA. O'rtacha iste'mol: agar harakat yo'q bo'lsa va ESP32 har 30 sekundda bir marta uyg'onib Firebase ga ma'lumot yuborsai, o'rtacha tok atigi 5-8 mA bo'ladi. 18650 li-ion batareya (3400 mAh) bilan tizim 17-28 kun avtonom ishlashi mumkin. Quyosh paneli (5V, 1W) qo'shilganda esa tizim cheksiz muddatga avtonom ishlaydi, chunki kunlik energiya ishlab chiqarish (5-6 soat × 200 mA = 1000-1200 mAh) tungi iste'moldan (12 soat × 8 mA = 96 mAh) 10 baravar ko'p. Bu hisob-kitoblar nazariy bo'lib, amaliy sinovlarda batareya quvvati 15-20% ga kamroq chiqdi, chunki WiFi ulanish vaqti va Firebase yozish operatsiyalari qo'shimcha energiya sarflaydi."),

    ("text", "ESP32 mikrokontrolleri 2016-yilda Xitoyning Espressif Systems kompaniyasi tomonidan ishlab chiqarilgan bo'lib, hozirgi kunda IoT sohasida eng mashhur va keng qo'llaniladigan platformalardan biri hisoblanadi. Uning asosida Tensilica Xtensa LX6 dual-core (ikki yadroli) protsessori yotadi, har bir yadro 240 MHz chastotada ishlaydi va mustaqil ravishda turli vazifalarni bajarishi mumkin — masalan, bitta yadro sensor o'qishni, ikkinchisi WiFi aloqasini boshqaradi. Harvard arxitekturasi tufayli buyruqlar va ma'lumotlar alohida shinalar (bus) orqali parallel uzatiladi, bu esa Von Neumann arxitekturasiga nisbatan ishlash tezligini sezilarli oshiradi. Xotira tizimi: 520 KB SRAM (200 KB DRAM dinamik ma'lumotlar uchun + 320 KB IRAM buyruqlar uchun) va 4 MB SPI Flash dastur xotirasida firmware saqlanadi. Simsiz aloqa imkoniyatlari: WiFi 802.11 b/g/n standartlari, 2.4 GHz chastotada 150 Mbps gacha tezlik va Bluetooth Low Energy (BLE) 4.2 versiyasi. Periferiya modullari: 34 ta GPIO (umumiy maqsadli kirish/chiqish) pin, 18 kanalli 12-bitli ADC (analog-raqamli konvertor), 2 kanalli 8-bitli DAC (raqamli-analog konvertor), 10 ta kapasitiv sensorli (touch) pin, SPI, I2C, UART, I2S interfeyslari, 16 kanalli PWM (pulsli kenglik modulyatsiyasi) va RTC (real-time clock) moduli. Energiya rejimi: deep sleep holatida atigi 10 μA iste'mol qiladi (yillab batareyada ishlashi mumkin), aktiv holatda WiFi bilan 160-260 mA. Mantiqiy daraja 3.3V, chip o'lchami QFN 6×6 mm paketda."),

    ("image", "esp32_pinout.png", "1.5-rasm. ESP32 DevKit mikrokontrolleri pin joylashuvi"),

    ("text", "Relay (o'rni almashtirgich) moduli — bu kichik boshqaruv signali orqali katta quvvatli yukni (lampochka, motor, isitgich) ulash yoki uzish imkonini beruvchi elektromexanik kalit hisoblanadi. Modul ichida asosiy ikki qism mavjud: katushka (coil) va kontakt mexanizmi. Katushkaga tok berilganda magnit maydoni hosil bo'ladi va bu maydon kontaktlarni mexanik ravishda tortib yopadi yoki ochadi. Xavfsizlik uchun optokuplyor (optocoupler) izolyatsiyasi qo'llaniladi — bu mikrokontrollerning past kuchlanishli (3.3V) qismini va yuqori kuchlanishli (220V) qismni elektrik jihatdan to'liq ajratadi, shu bilan mikrokontrollerni himoya qiladi. Boshqaruv qismida NPN tranzistor (odatda S8050) signalni kuchaytiradi — ESP32 ning 3.3V, 12 mA chiqishi to'g'ridan-to'g'ri katushkani boshqara olmaydi, tranzistor esa 5V dan 70 mA tok beradi. Flyback diod (1N4007) esa katushka o'chirilganda hosil bo'ladigan teskari EHK (elektr harakatlantiruvchi kuch) dan tranzistorni himoya qiladi — bu kuchlanish 200V gacha bo'lishi mumkin. Modul active LOW rejimida ishlaydi: LOW signal berilganda relay yoqiladi (ON), HIGH signal berilganda o'chadi (OFF). Kontaktlar: NO (normally open — odatda ochiq), NC (normally closed — odatda yopiq) va COM (common — umumiy). Yuklanish qobiliyati: 10A 250VAC yoki 10A 30VDC. Mexanik resurs 100000 tsikl, elektrik resurs 50000 tsikl (resistiv yuk bilan). Boshqaruv toki 15-20 mA."),

    ("image", "relay_module.png", "1.6-rasm. Relay moduli tuzilishi"),

    ("text", "Tizimning umumiy elektr sxemasida barcha komponentlar o'zaro bog'langan holda ishlaydi. ESP32 DevKit platasi markaziy boshqaruv elementi sifatida xizmat qiladi: GPIO4 pini RCWL-9610A ning TRIG piniga, GPIO16 ECHO piniga ulangan. GPIO34 (ADC1_CH6) TEMT6000 ning analog chiqishiga ulangan. GPIO26 relay modulining IN (kirish) piniga ulangan. Barcha komponentlar umumiy GND (yer) liniyasiga ulangan — bu juda muhim, chunki umumiy yer bo'lmasa analog o'lchovlar noto'g'ri bo'ladi va raqamli signallar ishlamaydi. Quvvatlantirish sxemasi: ESP32 USB orqali 5V oladi va ichki regulyator orqali 3.3V hosil qiladi. RCWL-9610A va TEMT6000 ESP32 ning 3.3V pinidan quvvatlanadi. Relay moduli alohida 5V manbaiga ulangan (USB dan), chunki relay katushkasi 5V talab qiladi. LED strip (yoki ko'cha chiroq) relay ning NO va COM kontaktlari orqali 220V tarmoqqa ulangan. Xavfsizlik choralari: relay moduli optokuplyor orqali izolyatsiyalangan, barcha 220V ulanishlar izolatsiyalangan terminal bloklari orqali amalga oshirilgan, tizim plastik korpusda joylashgan va IP54 himoya darajasiga ega."),

    ("text", "Debounce (shovqinni filtrlash) mexanizmi ultratovush sensoridan keladigan noto'g'ri va shovqinli signallarni aniqlash va bartaraf etish uchun qo'llaniladi. Shovqin sabablari ko'p va xilma-xil: kuchli shamol yoki havo oqimi sensorga ta'sir qilib yolg'on aks etish hosil qilishi, sensor ichidagi ko'p martalik aks etishlar (multipath reflection) noto'g'ri masofa ko'rsatishi, yaqin atrofdagi boshqa ultratovush manbalari (ko'rshapalaklar, boshqa sensorlar, sanoat uskunalari) interferensiya yaratishi mumkin. Tizimda majority voting (ko'pchilik ovozi) 2/3 algoritmi joriy etilgan: ketma-ket 3 ta o'lchov olinadi, har bir o'lchov orasida 50 ms pauza bilan (jami 150 ms). Agar 3 ta o'lchovdan kamida 2 tasi belgilangan threshold (chegara qiymati, masalan 200 sm) dan past bo'lsa — harakat bor deb hisoblanadi. Bu yondashuv false positive (yolg'on ijobiy — harakat yo'q bo'lganda bor deb aniqlash) natijalarni deyarli to'liq yo'q qiladi. Amaliy misol: agar o'lchovlar [150, 450, 120] sm bo'lsa — 3 tadan 2 tasi (150 va 120) threshold dan past, demak harakat aniqlangan va yoritgich yoqiladi. Agar o'lchovlar [450, 300, 420] sm bo'lsa — faqat bittasi (300) nisbatan past, lekin 2/3 ko'pchilik yo'q, demak harakat yo'q va yoritgich o'chiq qoladi. Bu oddiy, lekin juda samarali filtrlash usuli real-time embedded tizimlar uchun ideal hisoblanadi, chunki u minimal hisoblash resursi talab qiladi va deterministik natija beradi. Bundan tashqari, bu algoritm kengaytirilishi mumkin — masalan, 5 ta o'lchovdan 3 tasi (3/5 majority) yoki o'rtacha qiymat (averaging) usullari ham qo'llanilishi mumkin, lekin 2/3 usuli tezlik va aniqlik o'rtasida eng yaxshi muvozanatni ta'minlaydi."),

    ("text", "Hold timer (ushlab turish taymeri) mexanizmi yoritgichning tez-tez yonib-o'chishini oldini olish uchun ishlab chiqilgan muhim dasturiy yechim hisoblanadi. Har safar harakat aniqlanganda, millis() funksiyasi orqali joriy vaqt (millisekundlarda) lastMotionTime o'zgaruvchisiga saqlanadi. Asosiy dastur tsiklida (loop) doimiy ravishda (millis() - lastMotionTime < HOLD_TIME) sharti tekshiriladi: agar oxirgi harakatdan beri belgilangan vaqt (standart 5000 ms = 5 sekund) o'tmagan bo'lsa, yoritgich yoniq holatda qoladi. Bu mexanizm bir nechta muhim vazifani bajaradi: birinchidan, relay kontaktlarini tez-tez ulanish-uzilishdan himoya qiladi — har bir kommutatsiya kontaktlarni yemirilishiga olib keladi, 5 sekundlik kechikish esa kuniga minglab keraksiz kommutatsiyalarni yo'q qiladi va relay xizmat muddatini 3-5 baravar uzaytiradi. Ikkinchidan, foydalanuvchi qulayligini ta'minlaydi — odam o'rtacha 1.4 m/s tezlikda yurganda 5 sekund ichida 7 metr yo'l bosadi, bu sensor qamrov zonasidan (1.6 m diametr) chiqish va keyingi sensor zonasiga kirish uchun yetarli vaqt. Uchinchidan, energiya tejash va qulaylik o'rtasida optimal muvozanatni ta'minlaydi — juda qisqa timeout energiya tejaydi lekin foydalanuvchini noqulay qiladi, juda uzun timeout esa energiya isrof qiladi. Tajribada 5 sekund optimal qiymat ekanligi aniqlandi. Hold time qiymati Firebase Realtime Database orqali masofadan real-time o'zgartirilishi mumkin — administrator dashboard orqali 1 sekunddan 60 sekundgacha sozlashi mumkin, bu esa turli sharoitlarga moslashish imkonini beradi, masalan, gavjum ko'chalarda timeout uzaytiriladi, kam odamli hududlarda qisqartiriladi."),

    ("text", "Hysteresis (gisterezis) mexanizmi yorug'lik sensorining tebranishli (oscillating) signallarini bartaraf etish uchun qo'llaniladigan klassik muhandislik yechimi hisoblanadi. Bu Schmitt trigger (Shmitt triggeri) prinsipi asosida ishlaydi: tizimda bitta emas, balki ikkita alohida chegara qiymati belgilanadi — pastki chegara (lower threshold) 250 va yuqori chegara (upper threshold) 350. Agar sensor qiymati 250 dan pastga tushsa, tizim tun rejimiga o'tadi va harakat sensorini faollashtiradi. Agar qiymat 350 dan yuqoriga ko'tarilsa, kunduz rejimiga o'tadi va yoritgichni o'chiradi. 250 va 350 orasidagi 100 birliklik dead zone (o'lik zona) mavjud — bu zonada tizim oldingi holatini saqlab qoladi va hech qanday o'zgartirish qilmaydi. Bu mexanizm bulutli ob-havoda ayniqsa muhim ahamiyatga ega: bulut quyoshni yopganda sensor qiymati 320 ga tushadi, bulut o'tganda 340 ga ko'tariladi — oddiy bitta chegarali tizimda (masalan, 300) har bulut o'tganda yoritgich yonib-o'chib turgan bo'lar edi, bu esa energiya isrof qiladi va uskunani eskiradi. Hysteresis bilan esa 320 va 340 qiymatlari dead zone ichida bo'lgani uchun tizim barqaror qoladi. Analog sensorlar bilan ishlaydigan barcha professional sanoat tizimlarida (termostatlar, bosim regulyatorlari, yorug'lik boshqaruvchilari) hysteresis standart yechim sifatida qo'llaniladi va tebranish (oscillation) muammosini to'liq bartaraf etadi."),

    ("text", "Yuqorida tavsiflangan barcha mexanizmlar — debounce filtrlash, hold timer va hysteresis — birgalikda yaxlit algoritmni tashkil etadi. Tizim ishlash algoritmi quyidagi ketma-ketlikda amalga oshiriladi: avval TEMT6000 sensori orqali atrof yorug'lik darajasi o'lchanadi va hysteresis mexanizmi orqali kunduz yoki tun ekanligi aniqlanadi. Agar kunduz bo'lsa — tizim kutish rejimida qoladi va energiya tejaydi. Agar tun bo'lsa — RCWL-9610A ultratovush sensori faollashadi va har 500 ms da masofa o'lchaydi. O'lchov natijalari debounce filtri orqali tekshiriladi (3 ta o'lchovdan 2 tasi threshold dan past bo'lishi kerak). Agar harakat aniqlansa — relay yoqiladi va yoritgich yonadi, lastMotionTime yangilanadi. Agar harakat aniqlanmasa — hold timer tekshiriladi: agar 5 sekund o'tmagan bo'lsa yoritgich yoniq qoladi, agar o'tgan bo'lsa — relay o'chiriladi. Parallel ravishda ESP32 ning ikkinchi yadrosi Firebase bilan aloqa qiladi: sensor qiymatlarini yuboradi, boshqaruv buyruqlarini qabul qiladi. Bu algoritm sekundiga 2 marta (500 ms interval) to'liq tsiklni bajaradi va barcha qarorlarni 10 ms ichida qabul qiladi."),

    ("image", "flowchart_algorithm.png", "1.7-rasm. Tizim ishlash algoritmi blok-sxemasi"),
]
