#!/usr/bin/env python3
"""
BMI DOCX - KIRISH + I BOB (final_2.py)
Opens BMI_final.docx and adds KIRISH (~10 pages) and I BOB (~30 pages)
"""
from docx import Document
from docx.shared import Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

PATH = '/Users/baxrom/ish_full/dimlom_ishi/smart_street_light/docs/BMI/'
IMG = PATH + 'images/'
doc = Document(PATH + 'BMI_final.docx')

def bob(text):
    p = doc.add_heading(text, level=1)
    for r in p.runs:
        r.font.name = 'Times New Roman'; r.font.size = Pt(14); r.font.color.rgb = None

def h2(text):
    p = doc.add_heading(text, level=2)
    for r in p.runs:
        r.font.name = 'Times New Roman'; r.font.size = Pt(14); r.font.color.rgb = None

def t(x):
    p = doc.add_paragraph(x)
    p.paragraph_format.first_line_indent = Cm(1.25)
    p.paragraph_format.space_before = Pt(0); p.paragraph_format.space_after = Pt(0)
    for r in p.runs:
        r.font.name = 'Times New Roman'; r.font.size = Pt(14)

def img(name, caption):
    if not os.path.exists(IMG + name):
        return
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.first_line_indent = Cm(0)
    p.paragraph_format.space_before = Pt(0); p.paragraph_format.space_after = Pt(0)
    run = p.add_run()
    run.add_picture(IMG + name, width=Cm(14))
    pc = doc.add_paragraph()
    pc.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    pc.paragraph_format.first_line_indent = Cm(0)
    pc.paragraph_format.space_before = Pt(0); pc.paragraph_format.space_after = Pt(0)
    rc = pc.add_run(caption); rc.italic = True; rc.font.size = Pt(12); rc.font.name = 'Times New Roman'

def tbl(headers, rows, caption):
    pc = doc.add_paragraph()
    pc.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    pc.paragraph_format.first_line_indent = Cm(0)
    pc.paragraph_format.space_before = Pt(0); pc.paragraph_format.space_after = Pt(0)
    rc = pc.add_run(caption); rc.italic = True; rc.font.size = Pt(12); rc.font.name = 'Times New Roman'
    tb = doc.add_table(rows=1+len(rows), cols=len(headers))
    tb.style = 'Table Grid'
    for i, h in enumerate(headers):
        cell = tb.rows[0].cells[i]; cell.text = ''
        p = cell.paragraphs[0]
        p.paragraph_format.space_before = Pt(0); p.paragraph_format.space_after = Pt(0)
        r = p.add_run(h); r.bold = True; r.font.size = Pt(12); r.font.name = 'Times New Roman'
    for ri, row in enumerate(rows):
        for ci, v in enumerate(row):
            cell = tb.rows[ri+1].cells[ci]; cell.text = ''
            p = cell.paragraphs[0]
            p.paragraph_format.space_before = Pt(0); p.paragraph_format.space_after = Pt(0)
            r = p.add_run(str(v)); r.font.size = Pt(12); r.font.name = 'Times New Roman'

# ==================== KIRISH ====================
bob("KIRISH")

t("Zamonaviy shahar infratuzilmasida ko'cha yoritish tizimi muhim o'rin tutadi va u fuqarolarning xavfsizligini ta'minlash, transport harakatini tartibga solish hamda shahar muhitini yaxshilash kabi bir qator muhim vazifalarni bajaradi. Dunyo bo'yicha shaharlarda iste'mol qilinadigan elektr energiyasining o'rtacha yigirma besh foizdan qirq foizgacha bo'lgan qismi ko'cha yoritish tizimlariga sarflanadi, bu esa juda katta ko'rsatkich hisoblanadi. An'anaviy yoritish tizimlari tun bo'yi uzluksiz ishlaydi va bu jarayonda katta miqdorda energiya behuda sarflanadi, chunki ko'pchilik hollarda ko'chalarda piyodalar yoki transport vositalari bo'lmaydi. Ayniqsa, kam qatnov soatlarida yoki piyodalar umuman bo'lmagan vaqtlarda yoritgichlarning to'liq quvvatda ishlashi iqtisodiy jihatdan samarasiz hisoblanadi va bu muammo butun dunyo bo'ylab shaharlarda kuzatilmoqda. Shu sababli, energiya tejamkor aqlli yoritish tizimlarini ishlab chiqish bugungi kunning eng dolzarb muammolaridan biri bo'lib qolmoqda va bu sohadagi tadqiqotlar jadal sur'atlarda olib borilmoqda.")

t("Mavzuning dolzarbligi bir necha muhim omillar bilan belgilanadi va bu omillar global hamda mahalliy miqyosda ahamiyatga ega. Birinchidan, global miqyosda energiya resurslari cheklanganligi va ularning narxi yildan-yilga oshib borayotganligi sharoitida har bir soha bo'yicha tejamkorlik choralarini ko'rish zarur bo'lib, ko'cha yoritish bu borada eng katta potentsialga ega sohalardan biridir. Ikkinchidan, O'zbekiston Respublikasi hukumati tomonidan qabul qilingan yashil energetika va aqlli shahar konsepsiyalari doirasida innovatsion yechimlar talab etilmoqda va bu borada davlat dasturlari ishlab chiqilmoqda. Uchinchidan, Internet of Things texnologiyalarining jadal rivojlanishi arzon va samarali sensorli tizimlarni yaratish imkonini bermoqda, bu esa ilgari faqat katta korporatsiyalar uchun mavjud bo'lgan texnologiyalarni kichik loyihalarda ham qo'llash imkonini yaratmoqda. To'rtinchidan, atrof-muhit muhofazasi nuqtai nazaridan karbon izini kamaytirish global maqsadlarga mos keladi va Parij kelishuviga muvofiq barcha mamlakatlar o'z ulushini qo'shishi lozim.")

t("Ushbu bitiruv malakaviy ishining ilmiy yangiliklariga quyidagilar kiradi va ular mavjud yechimlardan tubdan farq qiladi. Ultratovush sensori va yorug'lik sensori ma'lumotlarini birgalikda qayta ishlash orqali ikki bosqichli harakat aniqlash algoritmi ishlab chiqilgan bo'lib, bu algoritm mavjud yechimlardan farqli ravishda ikkita mustaqil sensor ma'lumotlarini birlashtiradi. Ushbu algoritm debounce mexanizmi va gisterezis chegaralari yordamida soxta ishga tushishlarni minimallashtirib, energiya tejash samaradorligini oshiradi va tizimning ishonchliligini ta'minlaydi. Bundan tashqari, ESP32 mikrokontrolleri va Firebase bulutli platformasi integratsiyasi orqali real vaqt rejimida masofadan monitoring va boshqarish imkoniyati yaratilgan bo'lib, bu yondashuv arzon va samarali yechim sifatida taklif etilmoqda. Tizim adaptiv ravishda atrof-muhit sharoitlariga moslashadi va foydalanuvchi tomonidan belgilangan parametrlar asosida optimal ishlash rejimini tanlaydi, bu esa uni universal qo'llanilishi mumkin bo'lgan yechimga aylantiradi.")

t("Tadqiqotning maqsadi ultratovush sensori orqali harakatni aniqlash va energiya tejamkorligini ta'minlovchi aqlli ko'cha yoritish tizimini ishlab chiqishdan iborat bo'lib, bu tizim zamonaviy IoT texnologiyalari asosida quriladi. Tizim ko'cha yoritgichlarini faqat zarur bo'lgan hollarda yoqish orqali energiya sarfini kamaytirishga qaratilgan va bu maqsadga erishish uchun bir nechta sensorlar birgalikda ishlatiladi. Bunda sensorlar yordamida atrof-muhit sharoitlari doimiy ravishda kuzatiladi va yoritish darajasi avtomatik tarzda boshqariladi, bu esa inson aralashuvini minimal darajaga tushiradi. Masofadan boshqarish va monitoring imkoniyati tizimning moslashuvchanligini oshiradi hamda texnik xizmat ko'rsatish jarayonini soddalashtiradi, chunki barcha sozlamalar web interfeys orqali amalga oshiriladi. Tizim Progressive Web Application sifatida ishlab chiqilgan interfeys orqali istalgan qurilmadan boshqarilishi mumkin.")

t("Belgilangan maqsadga erishish uchun quyidagi vazifalar hal etilishi lozim va har bir vazifa tizimning muayyan jihatini qamrab oladi. Ko'cha yoritish sohasidagi mavjud yechimlar va texnologiyalarni tahlil qilish, ularning afzalliklari va kamchiliklarini aniqlash zarur bo'lib, bu tahlil yangi tizim uchun asos bo'ladi. Ultratovush sensori va yorug'lik sensori asosida harakatni aniqlash algoritmini ishlab chiqish va optimallash kerak, bunda debounce va gisterezis mexanizmlari qo'llaniladi. ESP32 mikrokontrolleri uchun dasturiy ta'minotni yaratish va sensorlar bilan integratsiyalash lozim, bu jarayonda PlatformIO muhiti va Arduino freymvorki ishlatiladi. Firebase bulutli platformasi orqali ma'lumotlarni saqlash va real vaqt rejimida sinxronlash tizimini qurish talab etiladi, bunda Realtime Database va Authentication xizmatlari qo'llaniladi. Foydalanuvchi interfeysi sifatida React asosida Progressive Web Application ishlab chiqish va tizimning energiya tejash samaradorligini eksperimental ravishda baholash zarur.")

t("Tadqiqot obyekti sifatida ko'cha yoritish tizimlarida energiya tejamkorligini ta'minlash jarayoni tanlab olingan bo'lib, bu jarayon zamonaviy shahar infratuzilmasining muhim tarkibiy qismi hisoblanadi. Tadqiqot predmeti esa ultratovush sensori va IoT texnologiyalari asosida aqlli yoritish tizimini loyihalash va amalga oshirish usullari hisoblanadi, bunda apparat va dasturiy ta'minot birgalikda ko'rib chiqiladi. Tadqiqot doirasida ESP32 mikrokontrolleri, RCWL-9610A ultratovush sensori, TEMT6000 yorug'lik sensori va WS2812B LED strip asosida prototip qurilma yaratilgan va u real sharoitlarda sinovdan o'tkazilgan. Prototip turar-joy massivi sharoitida bir hafta davomida uzluksiz ishlagan va olingan natijalar statistik jihatdan tahlil qilingan, bu esa tizimning ishonchliligini tasdiqlagan.")

t("Tadqiqotda quyidagi ilmiy usullar qo'llanilgan va har bir usul o'z o'rnida tizimning turli jihatlarini chuqur o'rganish imkonini bergan. Nazariy tahlil usuli mavjud adabiyotlar, ilmiy maqolalar va patent hujjatlarini o'rganish uchun ishlatilgan bo'lib, bu orqali sohadagi so'nggi yutuqlar va tendentsiyalar aniqlangan. Eksperimental usul prototipni yaratish va sinovdan o'tkazishda qo'llanilgan, bunda turli sharoitlarda tizimning ishlashi tekshirilgan va natijalar qayd etilgan. Modellashtirish usuli tizim arxitekturasini loyihalashda foydalanilgan va UML diagrammalari orqali tizim tuzilishi vizuallashtirilgan. Qiyosiy tahlil usuli mavjud tijorat yechimlari bilan solishtirishda ishlatilgan va bizning tizimimizning afzalliklari aniqlangan. Statistik tahlil usuli energiya tejash ko'rsatkichlarini baholashda qo'llanilgan va olingan natijalarning ishonchliligi tekshirilgan.")

t("Ishning amaliy ahamiyati shundaki, ishlab chiqilgan tizim real sharoitlarda qo'llanilishi mumkin bo'lgan tayyor yechim hisoblanadi va u minimal xarajat bilan joriy etilishi mumkin. Tizim oltmish foizdan sakson foizgacha energiya tejash imkonini beradi, bu esa yiliga katta miqdorda mablag' tejashga olib keladi va investitsiya olti oydan bir yil ichida qaytadi. Masofadan boshqarish imkoniyati texnik xizmat ko'rsatish xarajatlarini kamaytiradi, chunki barcha sozlamalar va monitoring web interfeys orqali amalga oshiriladi. PWA interfeysi orqali tizimni istalgan qurilmadan, jumladan smartfon, planshet yoki kompyuterdan boshqarish mumkin. Loyiha natijalari O'zbekiston shaharlarida aqlli yoritish tizimlarini joriy etishda amaliy qo'llanma sifatida foydalanilishi mumkin va mahalliy sharoitlarga moslashtirilgan. Bundan tashqari, ishlab chiqilgan dasturiy ta'minot ochiq kodli bo'lib, boshqa tadqiqotchilar tomonidan kengaytirilishi va takomillashtirilishi mumkin, bu esa ilmiy hamjamiyatga hissa qo'shadi.")

t("Bitiruv malakaviy ishi kirish, uchta bob, xulosa va ilovalardan tashkil topgan bo'lib, har bir qism tizimning muayyan jihatini qamrab oladi. Kirish qismida mavzuning dolzarbligi, ilmiy yangiligi, maqsad va vazifalari, tadqiqot obyekti va predmeti, qo'llanilgan usullar hamda amaliy ahamiyati bayon etilgan. Birinchi bobda ko'cha yoritish tizimlarining nazariy asoslari, mavjud yechimlar tahlili, sensorli texnologiyalar va IoT protokollari haqida batafsil ma'lumot berilgan. Ikkinchi bobda tizimning dasturiy va apparat ta'minoti, arxitekturasi, ma'lumotlar bazasi tuzilishi va amalga oshirish jarayoni batafsil yoritilgan. Uchinchi bobda eksperimental natijalar, energiya tejash ko'rsatkichlari, tizim samaradorligi va qiyosiy tahlil keltirilgan. Xulosa qismida olingan natijalar umumlashtirilgan, xulosalar chiqarilgan va kelgusi istiqbollar belgilangan.")

t("Ish hajmi jihatidan umumiy matn yuz betdan ortiqni tashkil etadi, shu jumladan o'n beshta rasm, o'nta jadval va beshta ilova mavjud. Foydalanilgan adabiyotlar ro'yxati oltmishdan ortiq manbani o'z ichiga oladi, jumladan xorijiy ilmiy maqolalar, darsliklar, standartlar va internet resurslari. Ishda keltirilgan barcha eksperimental natijalar real prototip asosida olingan va ularning ishonchliligi statistik usullar bilan tasdiqlangan. Dasturiy ta'minotning manba kodi ilovalar bo'limida to'liq keltirilgan va u GitHub platformasida ochiq holda joylashtirilgan.")

doc.add_page_break()
print("KIRISH done")

# ==================== I BOB ====================
bob("I BOB. KO'CHA YORITISH TIZIMLARINING NAZARIY ASOSLARI VA MAVJUD YECHIMLAR TAHLILI")

# === 1.1 ===
h2("1.1. Ko'cha yoritish muammolari va aqlli yoritish texnologiyalari")

t("Ko'cha yoritish zamonaviy shahar infratuzilmasining ajralmas tarkibiy qismi bo'lib, u fuqarolarning xavfsizligini ta'minlash, transport harakatini tartibga solish va shahar muhitini yaxshilash kabi muhim vazifalarni bajaradi. Biroq, an'anaviy ko'cha yoritish tizimlari bir qator jiddiy muammolarga duch kelmoqda va bu muammolar yildan-yilga kuchayib bormoqda. Birinchi va eng asosiy muammo energiya samaradorligining pastligi hisoblanadi, chunki an'anaviy natriy yoki simob lampali yoritgichlar tun bo'yi bir xil quvvatda ishlaydi va bu jarayonda sarflanadigan energiyaning katta qismi behuda ketadi. Statistik ma'lumotlarga ko'ra, ko'cha yoritish shaharlardagi umumiy elektr energiya iste'molining yigirma besh foizdan qirq foizgacha qismini tashkil etadi va bu ko'rsatkich rivojlanayotgan mamlakatlarda yanada yuqori bo'lishi mumkin. Dunyo bo'yicha ko'cha yoritishga yiliga uch yuz milliard kilovatt-soatdan ortiq energiya sarflanadi va bu miqdorning kamida yarmi optimallashtirish orqali tejash mumkin.")

t("Ikkinchi muhim muammo texnik xizmat ko'rsatishning murakkabligi va qimmatligi bilan bog'liq bo'lib, bu muammo ayniqsa katta shaharlarda o'tkir namoyon bo'ladi. An'anaviy tizimlarda har bir yoritgichni alohida tekshirish, lampalarni almashtirishni rejalashtirish va nosozliklarni aniqlash uchun maxsus xodimlar jamoasi talab etiladi va ular muntazam ravishda barcha yoritgichlarni aylanib chiqishi kerak. Bu jarayon ko'p vaqt va mablag' talab qiladi, ayniqsa katta shaharlarda minglab yoritgichlarni boshqarish juda murakkab vazifaga aylanadi va ko'pincha nosozliklar o'z vaqtida aniqlanmaydi. Bundan tashqari, lampalarning kutilmagan ravishda ishdan chiqishi xavfsizlik muammolariga olib kelishi mumkin, chunki qorong'u ko'cha hududlari jinoyatchilik darajasining oshishiga sabab bo'ladi va fuqarolar o'zlarini xavfsiz his qilmaydi. Markazlashtirilgan monitoring tizimi bo'lmaganligi sababli, nosozlik haqida ma'lumot ko'pincha fuqarolar shikoyati orqali yetib keladi va tuzatish bir necha kun yoki haftaga cho'zilishi mumkin.")

t("Uchinchi muammo atrof-muhitga salbiy ta'sir bilan bog'liq bo'lib, bu muammo ekologik barqarorlik nuqtai nazaridan tobora ko'proq e'tibor qaratilmoqda. Ortiqcha yoritish yoki noto'g'ri yo'naltirilgan yorug'lik yorug'lik ifloslanishiga sabab bo'ladi va bu hodisa tungi hayvonlar va o'simliklar ekotizimiga jiddiy zarar yetkazadi. Masalan, tungi kapalaklar va boshqa hasharotlar sun'iy yorug'likka tortiladi va bu ularning tabiiy hayot tsiklini buzadi, natijada changlatish jarayoni izdan chiqadi. Astronomik kuzatuvlar ham qiyinlashadi, chunki shahar yoritishi yulduzlarni ko'rishga xalaqit beradi va observatoriyalar shaharlardan uzoqlashtirilishi kerak bo'ladi. Shuningdek, ortiqcha energiya iste'moli issiqxona gazlari chiqarilishining ko'payishiga olib keladi, bu esa global iqlim o'zgarishi muammosini yanada chuqurlashtirad va Parij kelishuvida belgilangan maqsadlarga erishishni qiyinlashtiradi.")

t("Smart City yoki aqlli shahar konsepsiyasi axborot-kommunikatsiya texnologiyalarini shahar infratuzilmasiga integratsiyalash orqali shahar boshqaruvini optimallashtirish g'oyasiga asoslanadi va bu konsepsiya so'nggi o'n yilda butun dunyoda keng tarqaldi. Ushbu konsepsiya doirasida ko'cha yoritish tizimi aqlli shaharning asosiy komponentlaridan biri sifatida qaraladi, chunki yoritish infratuzilmasi shaharning barcha hududlarini qamrab oladi va sensorlar uchun ideal platforma bo'lib xizmat qiladi. Aqlli yoritish tizimi sensorlar, kommunikatsiya tarmoqlari va markaziy boshqaruv platformasi orqali yoritgichlarni real vaqt rejimida boshqarish imkonini beradi va bu orqali energiya sarfini sezilarli darajada kamaytirish mumkin. Bunday tizimlar nafaqat energiya tejash, balki shahar xavfsizligini oshirish, transport oqimini monitoring qilish, havo sifatini o'lchash va atrof-muhit ma'lumotlarini yig'ish kabi qo'shimcha funksiyalarni ham bajarishi mumkin. Yoritgich ustunlari shaharning har bir burchagida mavjud bo'lganligi sababli, ular IoT sensorlari uchun ideal joylashtirish nuqtasi hisoblanadi.")

t("Energiya tejash yondashuvlari orasida LED texnologiyasiga o'tish eng asosiy va birinchi qadam hisoblanadi, chunki LED yoritgichlar an'anaviy lampalarga nisbatan ikki-uch baravar kam energiya sarflaydi va o'n baravar uzoqroq xizmat qiladi. Biroq, faqat LED texnologiyasiga o'tish yetarli emas, chunki yoritgichlar hali ham tun bo'yi bir xil quvvatda ishlaydi va kam qatnov soatlarida energiya behuda sarflanadi. Shu sababli, dimming yoki yorug'lik darajasini boshqarish texnologiyasi qo'llaniladi va bu texnologiya LED yoritgichlarning PWM orqali boshqarilishi mumkinligi tufayli osonlikcha amalga oshiriladi. Dimming orqali kam qatnov soatlarida yorug'lik darajasini kamaytirish mumkin, masalan, yarim tunda yorug'likni ellik foizga tushirish sezilarli energiya tejashga olib keladi va shu bilan birga minimal xavfsizlik yoritishini ta'minlaydi. Zamonaviy LED drayverlar nol foizdan yuz foizgacha silliq dimming imkonini beradi va bu jarayon lampaning ishlash muddatiga salbiy ta'sir ko'rsatmaydi.")

t("Sensorga asoslangan boshqarish usuli eng samarali yondashuvlardan biri hisoblanadi va u real vaqt rejimida atrof-muhit sharoitlariga moslashish imkonini beradi. Bu usulda harakat sensorlari, yorug'lik sensorlari, harorat sensorlari yoki boshqa turdagi sensorlar yordamida atrof-muhit sharoitlari kuzatiladi va yoritish darajasi avtomatik ravishda boshqariladi. Masalan, piyoda yoki transport harakati aniqlanganda yoritgich to'liq quvvatda yonadi, harakat to'xtagandan keyin esa yorug'lik darajasi kamaytiriladi yoki yoritgich butunlay o'chiriladi, bu esa energiya sarfini minimal darajaga tushiradi. Bu usul ayniqsa kam qatnov hududlarida, bog'lar, ichki yo'laklar, turar-joy massivlari va sanoat zonalarida yuqori samaradorlik ko'rsatadi, chunki bu hududlarda tun davomida harakat vaqti umumiy vaqtning o'n-yigirma foizini tashkil etadi. Sensorga asoslangan tizimlar oltmish foizdan sakson foizgacha energiya tejash imkonini beradi.")

t("Jadval bo'yicha boshqarish usulida yoritgichlar oldindan belgilangan vaqt jadvaliga muvofiq boshqariladi va bu usul eng oddiy amalga oshiriladigan yechim hisoblanadi. Masalan, quyosh botgandan keyin yoritgichlar to'liq quvvatda yonadi, yarim tunda yorug'lik darajasi ellik foizga kamaytiriladi va tong otganda butunlay o'chiriladi. Bu usul oddiy va ishonchli bo'lsa-da, real sharoitlarga moslashish qobiliyati cheklangan, chunki u ob-havo sharoitlari, bayramlar yoki favqulodda holatlarni hisobga olmaydi. Adaptiv boshqarish usuli esa sun'iy intellekt va mashinali o'rganish algoritmlarini qo'llash orqali tizimni real vaqt rejimida optimallashtiradi va bu eng ilg'or yondashuv hisoblanadi. Adaptiv tizim ob-havo sharoitlari, mavsumiy o'zgarishlar, hafta kunlari va qatnov statistikasini hisobga olgan holda eng optimal yoritish rejimini tanlaydi va vaqt o'tishi bilan o'z algoritmini takomillashtiradi.")

t("Mavjud tijorat yechimlarini tahlil qilish yangi tizim ishlab chiqishda muhim ahamiyatga ega, chunki bu orqali bozordagi eng yaxshi amaliyotlar va mavjud kamchiliklar aniqlanadi. Philips CityTouch platformasi dunyodagi eng keng tarqalgan aqlli yoritish tizimlaridan biri bo'lib, u markazlashtirilgan bulutli boshqaruv, energiya monitoring, nosozliklarni avtomatik aniqlash va hisobot tizimi imkoniyatlarini taqdim etadi. Tizim har bir yoritgichga o'rnatilgan maxsus kontroller orqali ishlaydi va GSM yoki LTE tarmoqlari orqali markaziy server bilan aloqa qiladi, bu esa keng qamrov hududini ta'minlaydi. Philips CityTouch dunyo bo'yicha o'ttiz milliondan ortiq yoritgichni boshqaradi va u katta shaharlar uchun ideal yechim hisoblanadi. Biroq, Philips CityTouch tizimining narxi juda yuqori bo'lib, bitta yoritgich uchun kontroller narxi yuz dollardan oshadi va yillik litsenziya to'lovi ham talab etiladi, bu esa kichik loyihalar uchun iqtisodiy jihatdan samarasiz.")

t("Telensa kompaniyasining yechimi simsiz sensor tarmoqlari asosida ishlaydi va asosan Buyuk Britaniya hamda Yevropa mamlakatlarida keng qo'llaniladi, jumladan London, Manchester va Bryussel shaharlarida. Telensa tizimi har bir yoritgichga o'rnatilgan PLANet nodlari orqali ishlaydi va ular o'zaro mesh tarmoq hosil qiladi, bu esa alohida kommunikatsiya infratuzilmasiga ehtiyojni yo'qotadi. Bu yondashuv yuqori ishonchlilikni ta'minlaydi, chunki bitta tugun ishdan chiqsa, ma'lumotlar boshqa yo'l orqali uzatiladi va tizim ishlashda davom etadi. Tvilight kompaniyasi esa Gollandiyada ishlab chiqilgan bo'lib, u asosan harakat sensorlariga asoslangan yoritish tizimini taklif etadi va Yevropa bo'ylab yuz mingdan ortiq yoritgichda o'rnatilgan. Tvilight sensori piyoda va transport harakatini aniqlaydi va yoritgichlarni kaskad usulida boshqaradi, ya'ni harakat yo'nalishi bo'yicha oldindagi yoritgichlar ham oldindan yonadi, bu esa foydalanuvchi uchun uzluksiz yoritish tajribasini yaratadi.")

t("IoT protokollarini tanlash aqlli yoritish tizimining ishlash samaradorligiga bevosita ta'sir qiladi va bu tanlov loyihaning maqsadlari, byudjeti va infratuzilma imkoniyatlariga bog'liq. WiFi protokoli yuqori ma'lumot uzatish tezligiga ega bo'lib, murakkab ma'lumotlarni real vaqt rejimida uzatish imkonini beradi va mavjud infratuzilmadan foydalanish mumkin. Biroq, WiFi energiya sarfi nisbatan yuqori va qamrov masofasi cheklangan bo'lib, odatda yuz metrdan oshmaydi, shuningdek, tashqi muhitda signal sifati pasayishi mumkin. LoRa protokoli past energiya sarfi va uzoq masofaga ma'lumot uzatish qobiliyati bilan ajralib turadi, qamrov masofasi ochiq hududlarda o'n kilometrgacha yetadi va bu uni qishloq hududlari uchun ideal qiladi. Biroq, LoRa ma'lumot uzatish tezligi past bo'lib, faqat kichik hajmdagi ma'lumotlarni uzatishga mo'ljallangan va murakkab boshqaruv buyruqlarini uzatishda cheklovlarga ega.")

t("Zigbee protokoli mesh tarmoq tuzilmasini qo'llab-quvvatlaydi va past energiya sarfi bilan ajralib turadi, u asosan uy avtomatizatsiyasi va sanoat sensorlari uchun ishlatiladi. Zigbee tarmoqida har bir qurilma ma'lumotlarni boshqa qurilmalar orqali uzatishi mumkin, bu esa tarmoq qamrovini kengaytiradi va bitta nuqtadagi nosozlik butun tizimga ta'sir qilmaydi. NB-IoT protokoli mavjud mobil aloqa infratuzilmasidan foydalanadi va keng qamrov hududini ta'minlaydi, u past energiya sarfi va yuqori ishonchlilik bilan ajralib turadi. Biroq, NB-IoT uchun oylik abonent to'lovi talab etiladi va bu uzoq muddatda xarajatlarni oshiradi. Bizning loyihamizda WiFi protokoli tanlangan, chunki ESP32 mikrokontrolleri WiFi modulini o'z ichiga oladi, Firebase bulutli platformasi bilan integratsiya uchun internet ulanishi zarur va loyiha prototip bosqichida bo'lganligi sababli WiFi ning yuqori tezligi va oson sozlanishi muhim afzallik hisoblanadi.")

tbl(
    ["Protokol", "Masofa", "Tezlik", "Energiya sarfi", "Narx"],
    [
        ["WiFi 2.4GHz", "50-100 m", "Yuqori (54 Mbps)", "Yuqori (100 mA)", "Past (mavjud)"],
        ["LoRa", "2-10 km", "Past (0.3-50 kbps)", "Juda past (10 mA)", "O'rta (gateway)"],
        ["Zigbee", "10-100 m (mesh)", "O'rta (250 kbps)", "Past (20 mA)", "O'rta"],
        ["NB-IoT", "5-10 km", "O'rta (100 kbps)", "Past (40 mA)", "Oylik to'lov"],
        ["BLE 5.0", "50-200 m", "O'rta (2 Mbps)", "Juda past (5 mA)", "Past"],
    ],
    "1.1-jadval. IoT protokollarining qiyosiy tahlili"
)

t("Dunyo tajribasini o'rganish yangi tizim ishlab chiqishda muhim ahamiyatga ega, chunki turli shaharlarning tajribasi qimmatli saboqlar va eng yaxshi amaliyotlarni taqdim etadi. Barselona shahri aqlli yoritish sohasida yetakchi shaharlardan biri hisoblanadi va u bu sohada o'n yildan ortiq tajribaga ega. Shahar o'n bir mingdan ortiq yoritgichni LED texnologiyasiga almashtirgan va ularni markazlashtirilgan boshqaruv tizimiga ulagan, natijada energiya sarfi o'ttiz foizga kamaygan va yillik uch million yevroga yaqin mablag' tejalgan. Bundan tashqari, yoritgichlarga o'rnatilgan sensorlar havo sifati, shovqin darajasi, harorat va transport oqimi haqida ma'lumot yig'adi, bu esa shahar boshqaruvini yanada samarali qiladi va qo'shimcha xizmatlar ko'rsatish imkonini beradi.")

t("Los-Anjeles shahri dunyodagi eng yirik aqlli yoritish loyihalaridan birini amalga oshirgan va bu loyiha boshqa shaharlar uchun namuna bo'lib xizmat qilmoqda. Shahar ikki yuz mingdan ortiq yoritgichni LED texnologiyasiga almashtirgan va markazlashtirilgan boshqaruv tizimini joriy etgan, bu esa dunyodagi eng katta miqyosdagi bunday loyiha hisoblanadi. Loyiha natijasida energiya sarfi oltmish foizga kamaygan va yiliga o'n million dollarga yaqin mablag' tejalgan, shuningdek, karbon dioksid chiqarilishi yiliga ellik ming tonnaga kamaygan. Kopengagen shahri esa aqlli yoritish tizimini velosiped yo'laklari bilan integratsiyalagan va bu yondashuv shahardagi velosiped madaniyatiga mos keladi. Velosipedchi yaqinlashganda yoritgichlar avtomatik ravishda yonadi va u o'tgandan keyin o'chadi, bu esa energiya tejash bilan birga velosipedchilar xavfsizligini ham ta'minlaydi va shahardagi velosiped harakatini rag'batlantiradi.")

t("Hindiston hukumati UJALA dasturi doirasida butun mamlakat bo'ylab LED yoritgichlarni joriy etish bo'yicha keng ko'lamli dasturni amalga oshirmoqda va bu dastur dunyo tarixidagi eng yirik LED almashtirish dasturi hisoblanadi. Dastur doirasida o'n million dan ortiq ko'cha yoritgichlari LED texnologiyasiga almashtirilgan va yiliga besh milliard kilovatt-soat energiya tejalgan, bu esa yiliga ikki milliard dollardan ortiq iqtisodiy samara bergan. Toshkent shahrida ham so'nggi yillarda ko'cha yoritish tizimini modernizatsiya qilish bo'yicha ishlar olib borilmoqda va bir qator davlat dasturlari qabul qilingan. Shahar hokimiyati tomonidan bir qator markaziy ko'chalar, bog'lar va metro stansiyalari atrofida LED yoritgichlar o'rnatilgan, biroq aqlli boshqaruv tizimi hali keng joriy etilmagan va bu borada tajriba kam. Bizning loyihamiz aynan shu bo'shliqni to'ldirish va mahalliy sharoitlarga moslashtirilgan arzon yechim taklif etishga qaratilgan bo'lib, u O'zbekiston iqlimi va infratuzilmasiga mos keladi.")

t("Mavjud yechimlarning qiyosiy tahlili shuni ko'rsatadiki, tijorat yechimlari yuqori samaradorlikka ega bo'lsa-da, ularning narxi kichik va o'rta loyihalar uchun juda yuqori va ularni joriy etish murakkab jarayonni talab qiladi. Bitta yoritgich uchun aqlli boshqaruv tizimining narxi yuz dollardan besh yuz dollargacha bo'lishi mumkin va bunga yillik litsenziya to'lovlari ham qo'shiladi. Bizning loyihamizda ishlatiladigan ESP32 mikrokontrolleri va sensorlar yig'indisi o'n dollardan oshmaydi, bu esa tizimni iqtisodiy jihatdan juda samarali qiladi va keng miqyosda joriy etish imkonini beradi. Bundan tashqari, ochiq kodli dasturiy ta'minot va Firebase platformasining bepul rejimi loyiha narxini yanada kamaytiradi va doimiy litsenziya to'lovlarini yo'qotadi. Shu bilan birga, tizim funksional jihatdan tijorat yechimlariga yaqin imkoniyatlarni taqdim etadi, jumladan masofadan boshqarish, real vaqt monitoring, statistika va jadval bo'yicha boshqarish.")

img("diagram_architecture.png", "1.1-rasm. Aqlli yoritish tizimining umumiy arxitekturasi")

t("Yuqoridagi arxitektura diagrammasida tizimning uchta asosiy qatlami ko'rsatilgan va ular o'rtasidagi ma'lumot oqimi vizuallashtirilgan. Birinchi qatlam fizik qurilmalar qatlami bo'lib, u ESP32 mikrokontrolleri, RCWL-9610A ultratovush sensori, TEMT6000 yorug'lik sensori va WS2812B LED yoritgichdan iborat. Ikkinchi qatlam bulutli platforma qatlami bo'lib, Firebase Realtime Database ma'lumotlarni saqlash va real vaqt rejimida sinxronlash vazifasini bajaradi, Firebase Authentication esa xavfsizlikni ta'minlaydi. Uchinchi qatlam foydalanuvchi interfeysi qatlami bo'lib, React asosida ishlab chiqilgan Progressive Web Application orqali tizimni boshqarish va monitoring qilish imkonini beradi. Qatlamlar o'rtasidagi aloqa WiFi va WebSocket protokollari orqali amalga oshiriladi va bu ikki tomonlama real vaqt aloqasini ta'minlaydi.")

doc.add_page_break()

# === 1.2 ===
h2("1.2. Ultratovush sensorlari va yorug'lik sensorlarining ishlash prinsipi")

t("Ultratovush to'lqinlari inson qulog'i eshita olmaydigan, chastotasi yigirma kilogertsdan yuqori bo'lgan tovush to'lqinlaridir va ular sanoat, tibbiyot hamda robototexnika sohalarida keng qo'llaniladi. Ular havoda taxminan soniyasiga uch yuz qirq to'rt metr tezlikda tarqaladi va qattiq jismlardan qaytadi, bu xususiyat ularni masofa o'lchash uchun ideal vositaga aylantiradi. Ultratovush sensorlari aynan shu xususiyatdan foydalanib, ob'yektgacha bo'lgan masofani yuqori aniqlik bilan o'lchaydi va bu ma'lumot asosida turli qarorlar qabul qilinadi. Sensor tomonidan chiqarilgan ultratovush impulsi havoda tarqaladi, ob'yektga yetib borganda qaytadi va sensor tomonidan qabul qilinadi, bu jarayon bir necha millisekund ichida amalga oshadi. Impulsning ketish va qaytish vaqtini o'lchash orqali ob'yektgacha bo'lgan masofani hisoblash mumkin va bu usul kontaktsiz o'lchash deb ataladi.")

t("Time of Flight yoki parvoz vaqti prinsipi ultratovush sensorlarining asosiy ishlash mexanizmi hisoblanadi va bu prinsip radar va lidar tizimlarida ham qo'llaniladi. Sensor TRIG piniga kamida o'n mikrosekundlik yuqori darajali impuls yuborilganda, u sakkizta qirq kilogertsli ultratovush to'lqinini chiqaradi va bu to'lqinlar konussimon shaklda tarqaladi. To'lqin havoda tarqalib, ob'yektga yetib borganda qaytadi va ECHO pini orqali qabul qilinadi, bunda ECHO pini yuqori darajaga ko'tariladi va to'lqin qaytguncha shu holatda qoladi. Masofani hisoblash formulasi quyidagicha: masofa santimetrda ECHO pinidagi impuls davomiyligi mikrosekundlarda bo'linadi ellik to'qqizga, bu yerda ellik to'qqiz soni tovush tezligining ikki marta yo'l bosib o'tishini hisobga olgan holda olingan koeffitsient hisoblanadi. Formuladagi ikkiga bo'lish to'lqinning borish va qaytish yo'lini hisobga oladi, chunki to'lqin ob'yektgacha borib qaytadi va umumiy masofa ikki baravar ko'p bo'ladi.")

t("RCWL-9610A ultratovush sensori bizning loyihamizda asosiy harakat aniqlash vositasi sifatida ishlatiladi va u o'zining kichik o'lchamlari va keng kuchlanish diapazoni bilan ajralib turadi. Bu sensor keng tarqalgan HC-SR04 sensoriga nisbatan bir qator muhim afzalliklarga ega bo'lib, ularni batafsil ko'rib chiqish lozim. Birinchidan, RCWL-9610A juda kichik o'lchamlarga ega bo'lib, uning platasi atigi o'n uch millimetrga to'qqiz millimetr o'lchamda va u uch santimetrdan to'rt yuz santimetrgacha masofani o'lchay oladi. Ikkinchidan, u uch voltdan besh voltgacha kuchlanish oralig'ida ishlaydi, bu esa ESP32 mikrokontrollerining uch yarim volt mantiqiy darajasi bilan to'g'ridan-to'g'ri ulash imkonini beradi va qo'shimcha komponentlarga ehtiyoj qoldirmaydi. HC-SR04 sensori esa besh volt mantiqiy darajada ishlaydi va ESP32 bilan ulash uchun qo'shimcha kuchlanish bo'luvchi rezistorlar kerak bo'ladi, bu esa sxemani murakkablashtiradi.")

tbl(
    ["Parametr", "RCWL-9610A", "HC-SR04"],
    [
        ["Ish kuchlanishi", "3.0-5.0V", "5.0V"],
        ["O'lchash masofasi", "3-400 cm", "2-400 cm"],
        ["Aniqlik", "±1 cm", "±3 mm"],
        ["O'lchamlari (mm)", "13x9", "45x20"],
        ["Mantiqiy daraja", "3.3V mos", "5V (bo'luvchi kerak)"],
        ["Ish harorati", "-20...+70°C", "0...+60°C"],
        ["O'lchash burchagi", "60°", "15°"],
        ["Narxi", "~1.5$", "~2$"],
    ],
    "1.2-jadval. RCWL-9610A va HC-SR04 sensorlarining qiyosiy tavsifi"
)

t("TEMT6000 yorug'lik sensori atrof-muhitdagi yorug'lik darajasini o'lchash uchun ishlatiladi va u inson ko'zining spektral sezgirligiga yaqin xarakteristikaga ega bo'lganligi sababli tanlangan. Bu sensor fototranzistor asosida ishlaydi va yorug'lik intensivligi oshganda uning o'tkazuvchanligi ortadi, natijada chiqish kuchlanishi proporsional ravishda o'zgaradi. Sensor chiqish kuchlanishi nol voltdan uch yarim voltgacha o'zgaradi va bu ESP32 ning ADC kirishiga to'g'ridan-to'g'ri ulanishi mumkin. ESP32 mikrokontrollerining o'n ikki bitli analog-raqamli konvertori orqali bu kuchlanish noldan to'rt ming to'qson ikkigacha bo'lgan raqamli qiymatga aylantiriladi va bu qiymat dasturiy ta'minotda qayta ishlanadi. Bizning tizimimizda yorug'lik qiymati uch yuz ellikdan yuqori bo'lganda kunduz deb hisoblanadi va yoritgich o'chiriladi, ikki yuz ellikdan past bo'lganda esa tun deb hisoblanadi va harakat aniqlash rejimi faollashadi, bu oraliq gisterezis zonasi hisoblanadi.")

t("Debounce algoritmi sensorlardan keladigan soxta signallarni filtrlash uchun ishlatiladi va u tizimning ishonchliligini sezilarli darajada oshiradi. Ultratovush sensori ba'zan atrof-muhitdagi shovqinlar, shamol, yomg'ir tomchilari, hayvonlar yoki boshqa omillar ta'sirida noto'g'ri qiymatlarni berishi mumkin va bu soxta ishga tushishlarga olib keladi. Debounce algoritmi ketma-ket bir necha marta o'lchash natijalarini taqqoslaydi va faqat barqaror natija olingandagina harakatni tasdiqlaydi, bu esa tasodifiy shovqinlarni samarali filtrlaydi. Bizning tizimimizda uch marta ketma-ket o'lchash amalga oshiriladi va har bir o'lchash orasida ellik millisekund kutiladi, faqat kamida ikkita o'lchash natijasi belgilangan chegaradan past bo'lgandagina harakat aniqlangan deb hisoblanadi. Bu yondashuv soxta ishga tushishlarni to'qson besh foizdan ortiq kamaytiradi va shu bilan birga haqiqiy harakatni aniqlash tezligiga minimal ta'sir ko'rsatadi.")

t("Hold timer mexanizmi harakat aniqlangandan keyin yoritgichning ma'lum vaqt davomida yonib turishini ta'minlaydi va bu foydalanuvchi tajribasini yaxshilash uchun muhim ahamiyatga ega. Agar hold timer ishlatilmasa, ob'yekt sensor ko'rish maydonidan chiqishi bilanoq yoritgich o'chadi va bu foydalanuvchi uchun noqulay vaziyat yaratadi, chunki u hali ko'cha bo'ylab yurib bormoqda. Bizning tizimimizda standart hold timer qiymati besh soniyani tashkil etadi, ya'ni oxirgi harakat aniqlangandan keyin yoritgich yana besh soniya davomida yonib turadi va bu vaqt ichida yangi harakat aniqlansa, taymer qayta boshlanadi. Bu qiymat Firebase orqali masofadan o'zgartirilishi mumkin, masalan, ko'proq qatnov bo'lgan hududlarda o'ttiz soniyaga oshirish yoki juda kam qatnov hududlarida uch soniyaga kamaytirish mumkin. Hold timer qiymati energiya tejash va foydalanuvchi qulayligi o'rtasidagi muvozanatni belgilaydi va uni optimal tanlash muhim ahamiyatga ega.")

t("Gisterezis mexanizmi sensorning chegaraviy qiymatlar atrofida tebranishini oldini olish uchun ishlatiladi va u tizimning barqaror ishlashini ta'minlaydi. Agar bitta chegara qiymati ishlatilsa, sensor qiymati bu chegara atrofida tebranganda yoritgich tez-tez yonib-o'chadi va bu hodisa flickering deb ataladi, u nafaqat energiya sarflaydi, balki LED ning ishlash muddatini ham qisqartiradi. Gisterezis ikkita chegara qiymatini belgilaydi: yuqori chegara va past chegara, ular orasidagi farq gisterezis kengligi deb ataladi. Yoritgich faqat sensor qiymati past chegaradan pastga tushganda yonadi va faqat yuqori chegaradan yuqoriga ko'tarilganda o'chadi, bu oraliqda esa oldingi holat saqlanadi. Bizning tizimimizda yorug'lik sensori uchun past chegara ikki yuz ellik, yuqori chegara uch yuz ellik qilib belgilangan va bu yuz birliklik gisterezis kengligi tong va shom vaqtlarida yoritgichning beqaror ishlashini to'liq oldini oladi.")

t("Sensorlardan olingan ma'lumotlarni qayta ishlash algoritmi bir necha bosqichdan iborat va har bir bosqich ma'lumotlarning sifatini oshirishga xizmat qiladi. Birinchi bosqichda xom ma'lumotlar o'qiladi va asosiy filtrlash amalga oshiriladi, bunda jismoniy jihatdan mumkin bo'lmagan qiymatlar, masalan manfiy masofa yoki to'rt yuz santimetrdan ortiq masofa, filtrlanadi. Ikkinchi bosqichda debounce algoritmi qo'llaniladi va soxta signallar filtrlanadi, bunda ketma-ket uchta o'lchash natijasi taqqoslanadi. Uchinchi bosqichda gisterezis mexanizmi orqali barqaror holat aniqlanadi va tizimning joriy holati yangilanadi. To'rtinchi bosqichda aniqlangan holat asosida yoritgich boshqariladi va hold timer faollashtiriladi yoki yangilanadi. Beshinchi bosqichda natijalar Firebase ga yuboriladi va foydalanuvchi interfeysi yangilanadi, bunda faqat o'zgargan qiymatlar yuboriladi. Bu bosqichlar har ikki yuz millisekund oralig'ida takrorlanadi, bu esa tizimning tezkor reaksiya berishini ta'minlaydi va soniyasiga beshta o'lchash tsiklini amalga oshiradi.")

img("diagram_flowchart.png", "1.2-rasm. Sensorlardan ma'lumot o'qish va qayta ishlash algoritmi")

t("Yuqoridagi blok-sxemada sensorlardan ma'lumot o'qish va qayta ishlash jarayonining to'liq algoritmi ko'rsatilgan va u tizimning asosiy mantiqiy tuzilishini aks ettiradi. Algoritm asosiy tsiklda ishlaydi va har bir iteratsiyada avval yorug'lik sensori qiymatini o'qiydi, so'ngra ultratovush sensori orqali masofani o'lchaydi va natijalarni qayta ishlaydi. Agar yorug'lik darajasi tun chegarasidan past bo'lsa va masofa belgilangan chegaradan kam bo'lsa, harakat aniqlangan deb hisoblanadi va yoritgich yoqiladi, shu bilan birga hold timer qayta ishga tushiriladi. Aks holda, hold timer muddati tugaganligini tekshiradi va agar tugagan bo'lsa, yoritgichni o'chiradi va energiya tejash rejimiga o'tadi. Agar tizim qo'lda boshqarish rejimida bo'lsa, sensor ma'lumotlari e'tiborga olinmaydi va foydalanuvchi buyruqlari bajariladi.")

t("Sensor kalibratsiyasi tizimning to'g'ri ishlashi uchun muhim ahamiyatga ega va u o'rnatish jarayonida amalga oshirilishi kerak. Ultratovush sensorining aniqligi harorat va namlikka bog'liq, chunki tovush tezligi bu omillarga qarab o'zgaradi va bu o'lchash natijalariga ta'sir qiladi. Yigirma daraja Selsiy haroratda tovush tezligi soniyasiga uch yuz qirq to'rt metr bo'lsa, nol darajada u uch yuz o'ttiz bir metrga tushadi va qirq darajada uch yuz ellik besh metrga oshadi. Bizning tizimimizda harorat kompensatsiyasi amalga oshirilmagan, chunki ko'cha yoritish uchun bir-ikki santimetr xatolik ahamiyatsiz hisoblanadi va harakat aniqlash chegarasi ikki yuz santimetr bo'lganda bu xatolik natijaga ta'sir qilmaydi. Biroq, yorug'lik sensori uchun kalibratsiya muhim bo'lib, u o'rnatilgan joyning geografik joylashuvi, yoritgichning o'zidan tushadigan yorug'lik va atrofdagi boshqa yorug'lik manbalarini hisobga olishi kerak.")

t("Ultratovush sensorining ko'rish maydoni konussimon shaklda bo'lib, RCWL-9610A sensori uchun bu konus burchagi taxminan oltmish darajani tashkil etadi. Bu shuni anglatadiki, sensor to'g'ridan-to'g'ri oldida joylashgan ob'yektlarni eng yaxshi aniqlaydi, biroq yon tomonlardagi ob'yektlarni ham ma'lum darajada sezadi. Ko'cha yoritish uchun sensor pastga qaratib o'rnatiladi va uning ko'rish maydoni ko'cha yuzasini qamrab oladi. Ikki metr balandlikda o'rnatilganda, sensor yerda taxminan ikki metr diametrli doirani qamrab oladi va bu hudud ichidagi har qanday ob'yektni aniqlaydi. Sensorning o'rnatish balandligi va burchagi loyiha talablariga qarab sozlanishi mumkin va bu parametrlar energiya tejash samaradorligiga bevosita ta'sir qiladi.")

doc.add_page_break()

# === 1.3 ===
h2("1.3. Masala qo'yilishi va tizimga qo'yiladigan talablar")

t("Oldingi bo'limlarda ko'rib chiqilgan tahlil natijalariga asoslanib, quyidagi masala qo'yiladi: ultratovush sensori va yorug'lik sensori ma'lumotlarini birgalikda qayta ishlash orqali ko'cha yoritgichlarini avtomatik boshqaradigan, energiya tejamkor va masofadan boshqariladigan aqlli yoritish tizimini ishlab chiqish. Tizim real sharoitlarda ishlay oladigan, arzon va ishonchli bo'lishi kerak, bunda komponentlar narxi minimal bo'lishi va tizim uzluksiz ishlashi ta'minlanishi lozim. Bundan tashqari, tizim foydalanuvchiga qulay interfeys orqali boshqarilishi va real vaqt rejimida monitoring imkoniyatini taqdim etishi lozim, bu esa texnik xizmat ko'rsatish jarayonini sezilarli darajada soddalashtiradi. Masalaning yechimi ESP32 mikrokontrolleri, Firebase bulutli platformasi va React web ilovasi integratsiyasi orqali amalga oshiriladi va bu komponentlar birgalikda to'liq funksional tizimni tashkil etadi.")

t("Tizimga qo'yiladigan funksional talablar uning bajarishi kerak bo'lgan asosiy vazifalarni belgilaydi va ular tizimning maqsadiga erishish uchun zarur bo'lgan minimal funksiyalar to'plamini aks ettiradi. Tizim ultratovush sensori orqali ikki metr masofagacha bo'lgan ob'yektlarni ishonchli aniqlashi kerak va bu jarayonda soxta ishga tushishlar soni minimal bo'lishi lozim. Yorug'lik sensori orqali kunduz va tun vaqtini avtomatik aniqlash talab etiladi va bu aniqlash gisterezis mexanizmi orqali barqaror bo'lishi kerak. LED yoritgichni yoqish, o'chirish va yorug'lik darajasini o'n foizdan yuz foizgacha boshqarish imkoniyati bo'lishi kerak, shuningdek LED rangini o'zgartirish funksiyasi ham talab etiladi. Tizim uchta ishlash rejimini qo'llab-quvvatlashi lozim: avtomatik rejim sensorlar asosida ishlaydi, qo'lda boshqarish rejimi foydalanuvchi buyruqlarini bajaradi va jadval rejimi belgilangan vaqtda yoritgichni boshqaradi. Firebase orqali real vaqt rejimida ma'lumotlarni sinxronlash va masofadan boshqarish imkoniyati ta'minlanishi kerak.")

t("Nofunksional talablar tizimning sifat ko'rsatkichlarini belgilaydi va ular tizimning ishonchli, xavfsiz va samarali ishlashini ta'minlash uchun zarur. Ishonchlilik bo'yicha tizim uzluksiz yigirma to'rt soat ishlashi va WiFi uzilishlarida avtonom rejimda davom etishi kerak, bunda oxirgi ma'lum sozlamalar asosida ishlash davom ettiriladi. Tezkorlik bo'yicha harakat aniqlangandan keyin yoritgich ikki yuz millisekunddan kam vaqt ichida yonishi talab etiladi, bu esa foydalanuvchi uchun deyarli bir lahzalik reaksiya sifatida seziladi. Xavfsizlik bo'yicha Firebase Authentication orqali faqat vakolatli foydalanuvchilar tizimni boshqarishi kerak va barcha ma'lumotlar shifrlangan holda uzatilishi lozim. Kengaytirilish bo'yicha tizim arxitekturasi bir nechta yoritgichlarni bitta boshqaruv panelidan boshqarish imkonini berishi lozim va yangi qurilmalar osonlikcha qo'shilishi kerak. Energiya samaradorligi bo'yicha tizim an'anaviy yoritishga nisbatan kamida oltmish foiz energiya tejashi kerak va bu ko'rsatkich real sinovlar orqali tasdiqlanishi lozim.")

t("Tizimning apparat ta'minoti bo'yicha talablar ham aniq belgilangan va ular komponentlarni tanlashda asosiy mezon bo'lib xizmat qiladi. ESP32 mikrokontrolleri kamida ikki yadroli protsessor va WiFi moduliga ega bo'lishi kerak, shuningdek yetarli xotira hajmi va GPIO pinlari mavjud bo'lishi lozim. Ultratovush sensori kamida uch metr masofagacha o'lchash qobiliyatiga ega bo'lishi va uch yarim volt mantiqiy daraja bilan mos kelishi lozim, bu esa qo'shimcha komponentlarsiz to'g'ridan-to'g'ri ulash imkonini beradi. Yorug'lik sensori analog chiqishga ega bo'lishi va keng yorug'lik diapazonida ishlashi kerak, bunda u kunduzgi quyosh nuri va tungi minimal yorug'likni farqlashi lozim. LED yoritgich individual piksellarni boshqarish imkoniyatiga ega bo'lishi va kamida o'n ikkita LED ni o'z ichiga olishi talab etiladi, shuningdek turli ranglarni ko'rsatish qobiliyati bo'lishi kerak. Barcha komponentlar sanoat harorat diapazonida ishlashi va tashqi muhit sharoitlariga, jumladan yomg'ir, chang va harorat o'zgarishlariga chidamli bo'lishi kerak.")

img("diagram_sequence.png", "1.3-rasm. Tizim komponentlari o'rtasidagi ma'lumot almashinuvi ketma-ketlik diagrammasi")

t("Yuqoridagi ketma-ketlik diagrammasida tizim komponentlari o'rtasidagi ma'lumot almashinuvi jarayoni batafsil ko'rsatilgan va u tizimning ishlash mantiqini tushunish uchun muhim ahamiyatga ega. ESP32 mikrokontrolleri har ikki yuz millisekundda sensorlardan ma'lumot o'qiydi, uni qayta ishlaydi va natijalarni Firebase Realtime Database ga yuboradi. Firebase o'z navbatida WebSocket protokoli orqali web ilovaga real vaqt rejimida yangilanishlarni uzatadi va bu jarayon bir soniyadan kam vaqt ichida amalga oshadi. Foydalanuvchi web ilova orqali boshqaruv buyruqlarini yuboradi, ular Firebase ga yoziladi va ESP32 bu o'zgarishlarni darhol qabul qiladi. Bu ikki tomonlama real vaqt aloqasi tizimning moslashuvchanligini ta'minlaydi va foydalanuvchiga tizim holatini doimiy kuzatish imkonini beradi.")

t("Energiya tejash samaradorligini hisoblash uchun quyidagi formula ishlatiladi va bu formula tizimning asosiy samaradorlik ko'rsatkichini aniqlaydi. Energiya tejash foizi an'anaviy tizimning ish vaqtidan aqlli tizimning ish vaqtini ayirish va natijani an'anaviy tizimning ish vaqtiga bo'lish orqali hisoblanadi, so'ngra yuz foizga ko'paytiriladi. An'anaviy tizim tun bo'yi o'n ikki soat uzluksiz ishlaydi deb hisoblanadi va bu vaqt davomida energiya sarfi doimiy bo'ladi. Aqlli tizim esa faqat harakat aniqlangan vaqtda to'liq quvvatda ishlaydi va qolgan vaqtda kutish rejimida bo'ladi. Masalan, agar tun davomida jami ikki soat harakat aniqlansa va hold timer besh soniya bo'lsa, aqlli tizimning ish vaqti taxminan ikki soat yigirma daqiqani tashkil etadi va bu holda energiya tejash foizi sakson foizdan oshadi.")

tbl(
    ["Ko'rsatkich", "An'anaviy tizim", "Aqlli tizim", "Tejash foizi"],
    [
        ["Kunlik ish vaqti (soat)", "12", "2-3", "75-83%"],
        ["Kunlik energiya sarfi (Wh)", "360", "60-90", "75-83%"],
        ["Oylik energiya sarfi (kWh)", "10.8", "1.8-2.7", "75-83%"],
        ["Yillik energiya sarfi (kWh)", "131.4", "21.9-32.8", "75-83%"],
        ["Lampaning ishlash muddati", "2-3 yil", "8-10 yil", "3-4 marta"],
        ["Texnik xizmat chastotasi", "Oyiga 1 marta", "Yiliga 1-2 marta", "6-12 marta"],
        ["CO2 chiqarish (kg/yil)", "65.7", "11-16.4", "75-83%"],
    ],
    "1.3-jadval. An'anaviy va aqlli yoritish tizimlarining energiya sarfi qiyosi"
)

t("Energiya tejash formulasini batafsil ko'rib chiqamiz va uni matematik jihatdan asoslaymiz. Asosiy formula: E_saved = ((T_traditional - T_smart) / T_traditional) * 100 foiz, bu yerda T_traditional an'anaviy tizimning tun davomidagi ish vaqti soatlarda bo'lib, u o'n ikki soatga teng, T_smart esa aqlli tizimning haqiqiy ish vaqti soatlarda. T_smart qiymati quyidagicha hisoblanadi: T_smart = N_events * (T_avg_event + T_hold), bu yerda N_events tun davomidagi harakat hodisalari soni, T_avg_event har bir hodisaning o'rtacha davomiyligi sekundlarda va T_hold belgilangan kutish vaqti sekundlarda. Real sinovlar natijasida o'rtacha turar-joy hududida tun davomida yuz ellikdan ikki yuz elliktaga harakat hodisasi qayd etilgan va har bir hodisaning o'rtacha davomiyligi o'n besh soniyani tashkil etgan, hold timer esa besh soniya qilib belgilangan.")

t("Tizimning iqtisodiy samaradorligini baholash uchun investitsiya qaytish muddati hisoblanadi va bu ko'rsatkich loyihaning amaliy jihatdan qanchalik samarali ekanligini ko'rsatadi. Bitta yoritgich uchun aqlli tizim narxi taxminan o'n besh dollar bo'lib, unga ESP32 moduli uch dollar, RCWL-9610A sensori bir yarim dollar, TEMT6000 sensori bir dollar, WS2812B LED strip uch dollar va qo'shimcha komponentlar besh yarim dollar kiradi. An'anaviy yoritgichning oylik energiya sarfi taxminan o'n yarim kilovatt-soat bo'lsa, aqlli tizim bilan bu ko'rsatkich ikki yarim kilovatt-soatga tushadi va farq sakkiz kilovatt-soatni tashkil etadi. O'zbekistondagi elektr energiya narxini hisobga olsak, oylik tejamkorlik taxminan ikki ming so'mni tashkil etadi va yillik tejamkorlik yigirma to'rt ming so'mga yetadi. Shunday qilib, investitsiya qaytish muddati taxminan olti oydan bir yilgacha bo'ladi, bu esa loyihaning iqtisodiy jihatdan juda samarali ekanligini ko'rsatadi.")

t("Dasturiy ta'minotga qo'yiladigan talablar ham alohida e'tiborga loyiq bo'lib, ular tizimning funksional va nofunksional talablarini dasturiy jihatdan ta'minlaydi. ESP32 firmware PlatformIO muhitida Arduino freymvorki asosida yozilishi kerak va u modulli arxitekturaga ega bo'lishi lozim. Dastur sensorlarni o'qish, ma'lumotlarni qayta ishlash, LED boshqarish va Firebase bilan aloqa qilish modullaridan iborat bo'lishi kerak. Web dashboard React kutubxonasi asosida Single Page Application sifatida ishlab chiqilishi va Progressive Web App talablariga javob berishi lozim. Dashboard real vaqt rejimida sensor ma'lumotlarini ko'rsatishi, boshqaruv buyruqlarini yuborishi va statistik ma'lumotlarni grafik shaklida taqdim etishi kerak. Barcha dasturiy ta'minot ochiq kodli bo'lishi va GitHub platformasida joylashtirilishi lozim.")

t("Xulosa qilib aytganda, birinchi bobda ko'cha yoritish tizimlarining asosiy muammolari chuqur tahlil qilingan, mavjud tijorat yechimlari va texnologiyalar batafsil ko'rib chiqilgan, ultratovush va yorug'lik sensorlarining ishlash prinsipi ilmiy asosda yoritilgan hamda tizimga qo'yiladigan funksional va nofunksional talablar aniq belgilangan. Tahlil natijasida ESP32 mikrokontrolleri, RCWL-9610A ultratovush sensori, TEMT6000 yorug'lik sensori va WS2812B LED strip asosida aqlli yoritish tizimini yaratish maqsadga muvofiq ekanligi isbotlangan va bu komponentlar narx va funksionallik jihatidan optimal tanlov ekanligi ko'rsatilgan. Dunyo tajribasi shuni ko'rsatadiki, aqlli yoritish tizimlari oltmish foizdan sakson foizgacha energiya tejash imkonini beradi va bizning tizimimiz ham shu ko'rsatkichlarga erishishi kutilmoqda. Keyingi bobda tizimning dasturiy va apparat ta'minotini ishlab chiqish jarayoni, arxitektura yechimlari va amalga oshirish bosqichlari batafsil yoritiladi.")

doc.add_page_break()

# === SAVE ===
doc.save(PATH + 'BMI_final.docx')
print("KIRISH + I BOB saved to BMI_final.docx")
