[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
upload_port = /dev/cu.usbserial-0001
upload_speed = 115200
lib_deps =
    mobizt/Firebase ESP32 Client@^4.4.17
    fastled/FastLED@^3.6.0
